
on: [push]

jobs:

    build:
        runs-on: windows-latest

        steps:
        - name: msbuild setup
          uses: microsoft/setup-msbuild@v1.0.0

        - name: vstest setup
          uses: darenm/Setup-VSTest@v1

        - name: checkout 
          uses: actions/checkout@master 

        - name: dir
          run:  get-childitem

        - name: env
          run:  set
          shell: cmd

        - name: compile 
          run:  msbuild DirectionReduction.sln /t:Clean,Rebuild /p:Configuration=Debug /p:Platform=Win32

        - name: test 
          run:  vstest.console.exe bin\DirectionReduction.dll 


